# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ManyToManyField(blank='True', related_name='friends', to='users.User'),
        ),
    ]
